# Rules found at https://realm.github.io/SwiftLint/rule-directory.html

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - nesting
  - cyclomatic_complexity
  - trailing_comma

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

function_body_length:
  warning: 80
  error: 120
