# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Print Stuff
      run: |
       echo Hello, world!
       echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE
       ls $GITHUB_WORKSPACE

    - name: Mint Cache
      id: mint-cache
      uses: actions/cache@master
      with:
        path: |
          /usr/local/Cellar/mint
          /usr/local/lib/mint/packages
        key: ${{ runner.os }}-mint-2-${{ hashFiles('CookSmart/BuildTools/Mintfile') }}

    - name: Homebrew Cache
      id: homebrew-cache
      uses: actions/cache@master
      with:
        path: |
          ~/Library/Caches/Homebrew
          /usr/local/Homebrew
        key: ${{ runner.os }}-homebrew-v2

    - name: Install Mint
      if: steps.mint-cache.outputs.cache-hit != 'true'
      run: |
        brew update
        brew link mint || brew install mint
        brew cleanup

    - name: Mint Bootstrap
      run: |
        brew link mint
        cd CookSmart/BuildTools
        mint bootstrap -v
