name: Cake Tests
on: pull_request
jobs:
  test:
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Mint Cache
      id: mint-cache
      uses: actions/cache@master
      with:
        path: |
          /usr/local/Cellar/mint
          /usr/local/lib/mint/packages
        key: ${{ runner.os }}-mint-2-${{ hashFiles('CookSmart/BuildTools/Mintfile') }}

    - name: Homebrew Cache
      id: homebrew-cache
      if: steps.mint-cache.outputs.cache-hit != 'true'
      uses: actions/cache@master
      with:
        path: |
          ~/Library/Caches/Homebrew
          /usr/local/Homebrew
        key: ${{ runner.os }}-homebrew-v2

    - name: Install Mint
      if: steps.mint-cache.outputs.cache-hit != 'true'
      run: |
        brew update
        brew link mint || brew install mint
        brew cleanup

    - name: Mint Bootstrap
      run: |
        brew link mint
        cd $GITHUB_WORKSPACE/CookSmart/BuildTools
        mint bootstrap -v
    
    - name: Run Tests
      run: |
        cd $GITHUB_WORKSPACE/CookSmart
        bundle exec fastlane testlane

